apiVersion: v1
kind: Service
metadata:
  name: ngnix
  namespace: default
spec:
  selector:
    app: ngnix
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: ngnix
    protocol: TCP
    port:80 
    targetPort:80 
    